name: driver
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # firebase
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  firebase_messaging: ^15.2.4
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  geocoding: ^3.0.0
  flutter_local_notifications: ^19.0.0
  googleapis_auth: ^1.6.0

  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  get: ^4.7.2
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  country_code_picker: ^3.2.0
  google_maps_flutter: ^2.11.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  bottom_picker: ^2.11.2

  flutter_dash: ^1.0.0
  provider: ^6.1.2
  dotted_border: ^2.1.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  flutter_email_sender: ^7.0.0
  flutter_html: any
  map_launcher: ^3.5.0
  google_maps_place_picker_mb: ^3.1.2
  badges: ^3.1.2
  location: any

  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.4.1

  mask_text_input_formatter: ^2.9.0
  firebase_crashlytics: ^4.3.6

  http: any
  rxdart: any
  geolocator: ^10.1.0
  package_info_plus: any
dependency_overrides:
  webview_flutter: ^4.8.0
  http: ^1.3.0
  google_api_headers: ^4.4.3
  package_info_plus: ^8.3.0
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/
